/**
 * Match Engine V2 - 2D Coordinate System Types
 * 
 * Extends base engine types with spatial positioning, movement AI,
 * and visual event generation for canvas-based match visualization.
 */

import type { PlayerState, TeamState, MatchState, MatchEventLog } from '../types';

// ============================================================
// TEAM CONTEXT (Per-Tick Game State)
// ============================================================

/**
 * TeamContext - Comprehensive per-tick game state
 * Used by role-intent modules to make decisions
 * 
 * Phase represents current game situation:
 * - 'ATTACK': Ball in possession, moving toward opponent goal
 * - 'DEFEND': Ball in opponent possession, in defensive area
 * - 'TRANSITION_TO_ATTACK': Just won ball, transitioning to attack
 * - 'TRANSITION_TO_DEFEND': Just lost ball, transitioning to defense
 * - 'BUILD_UP': Possession in own half, constructing play
 * - 'COUNTER_ATTACK': Fast transition with 3+ pass advantage
 * - 'SET_PIECE': Free kick / Corner / Throw-in
 * - 'SETTLED_DEFENSE': Opponent has ball, settled defensive shape
 */
export type GamePhase =
    | 'ATTACK'
    | 'DEFEND'
    | 'TRANSITION_TO_ATTACK'
    | 'TRANSITION_TO_DEFEND'
    | 'BUILD_UP'
    | 'COUNTER_ATTACK'
    | 'SET_PIECE'
    | 'SETTLED_DEFENSE';

/**
 * Pressure level (0-100) indicates how aggressively team should press
 */
export type PressureLevel = number; // 0-100

/**
 * DefensiveLineHeight (0-100) indicates where defense should sit
 * 0-25: Deep defense, sit back
 * 25-50: Mid-block
 * 50-75: High press
 * 75-100: Very high press / offside trap
 */
export type DefensiveLineHeight = number; // 0-100

/**
 * BallSide indicates which half of field ball is in
 * DEFENSIVE: Ball in own half (X < 50)
 * ATTACKING: Ball in opponent half (X >= 50)
 */
export type BallSide = 'DEFENSIVE' | 'ATTACKING';

/**
 * TeamContext provides strategic framework for all 11 players
 */
export interface TeamContext {
    tick: number;
    minute: number;
    phase: GamePhase;
    pressure: PressureLevel;         // How aggressive (0-100)
    lineHeight: DefensiveLineHeight; // Where to defend (0-100)
    ballSide: BallSide;              // Which half
    ballPosition: SpatialPosition;   // Current ball coords
    
    // Support lanes (defensive midfield, wing lanes, etc.)
    // Can be populated by midfield intent modules
    supportLanes?: {
        defensive: SpatialPosition[];  // DMC/DM anchor positions
        wings: SpatialPosition[];       // MR/ML lane positions
        forward: SpatialPosition[];     // AMC/AML/AMR positions
    };
    
    // Transition flags
    transitionMode?: 'FAST_BREAK' | 'SETTLED' | 'COUNTER_PRESS';
    
    // Scoring/winning state (affects mentality)
    scoreState?: {
        isLeading: boolean;
        isDraw: boolean;
        isTrailing: boolean;
        minutesRemaining: number;
    };
}

// ============================================================
// SPATIAL POSITIONING
// ============================================================

/**
 * 2D position on the field (0-100 normalized coordinates)
 * X-axis: 0 = Home goal, 100 = Away goal (field length)
 * Y-axis: 0 = Left touchline, 100 = Right touchline (field width)
 */
export interface SpatialPosition {
    x: number;  // 0-100 (length)
    y: number;  // 0-100 (width)
}

/**
 * Velocity vector for movement simulation
 */
export interface Velocity {
    dx: number;  // X-axis velocity (units per tick)
    dy: number;  // Y-axis velocity (units per tick)
}

// ============================================================
// ROLE INTENT SYSTEM (Phase 2+)
// ============================================================

/**
 * RoleJob - What a player should do this tick
 * Used by role-intent modules to generate decisions
 */
export type RoleJob =
    | 'MARK'              // Close down specific opponent
    | 'PRESS'             // Chase ball carrier aggressively
    | 'SUPPORT'           // Move to support possession play
    | 'DEFEND'            // Hold defensive position/line
    | 'ATTACK'            // Move toward goal/opponent goal
    | 'POSITION'          // Move to tactical position
    | 'COVER'             // Cover space vacated by teammate
    | 'OFFSIDE_TRAP';     // Hold offside line

export type PlayerPhaseState = 'DEFENDING' | 'IN_POSSESSION' | 'ON_BALL';

/**
 * RoleIntent - Per-player decision for this tick
 * Generated by role-specific intent modules
 */
export interface RoleIntent {
    // Core decision
    job: RoleJob;                      // What to do
    targetPosition: SpatialPosition;   // Where to move
    
    // Scoring & priority
    priority: number;                  // 1-100 (goal importance)
    utilityScore: number;              // 0-100 (quality of this decision)
    
    // Context & debug
    context: string;                   // Why chosen ("close to ball", "support FW", etc.)
    confidence?: number;               // 0-1 (certainty of decision)
    
    // Optional modifiers
    intensity?: number;                // 0-100 (how hard to press/attack)
    markingTarget?: string;            // Player ID to mark (if job=MARK)
    supportTarget?: string;            // Player ID to support (if job=SUPPORT)
}

/**
 * Phase 4: Scored pass option for intelligent target selection
 */
export interface PassOption {
    receiver: V2PlayerState;
    distance: number;
    successProbability: number;  // 0-1
    riskLevel: number;           // 0 (safe) - 1 (risky)
    urgency: number;             // 0-1 (time/pressure critical)
    utility: number;             // Weighted score (higher is better)
}

/**
 * Phase 5: Coordinated defensive assignment per tick
 */
export interface DefensiveAssignment {
    assigner: V2PlayerState;
    presser?: V2PlayerState;
    cover?: V2PlayerState;
    lineHolders: V2PlayerState[];
    priority: number;
}

// ============================================================
// EXTENDED PLAYER STATE
// ============================================================

/**
 * V2 Player State - Extends base PlayerState with spatial data
 */
export interface V2PlayerState extends PlayerState {
    side: TeamKey;

    // Spatial positioning
    position2D: SpatialPosition;      // Current position on field
    targetPosition: SpatialPosition;  // AI target position
    velocity: Velocity;               // Current movement velocity
    
    // Movement state
    isMovingToBall: boolean;          // Chasing ball
    isMarking: string | null;         // Player ID being marked
    movementSpeed: number;            // Current speed (pace-based)
    
    // Visual state
    isSprinting: boolean;             // Show sprint animation
    facingDirection: number;          // Degrees (0-360)

    // Role presets — read by specialist modules each tick to apply movement config
    attackingRolePreset?: string | null;
    defensiveRolePreset?: string | null;
}

// ============================================================
// BALL STATE
// ============================================================

/**
 * V2 Ball State with 2D physics
 */
export interface V2BallState {
    position: SpatialPosition;        // Current ball position
    velocity: Velocity;               // Ball velocity
    z: number;                        // Height (0 = ground, 100 = max)
    possession: 'home' | 'away';
    carrier: V2PlayerState | null;    // Player carrying ball
    
    // Trajectory preview (for passes/shots)
    trajectory?: SpatialPosition[];   // Predicted path
    targetPosition?: SpatialPosition; // Final destination
}

// ============================================================
// VISUAL EVENTS
// ============================================================

/**
 * Visual event types for canvas rendering
 */
export type VisualEventType = 
    | 'GOAL'
    | 'SHOT'
    | 'PASS'
    | 'TACKLE'
    | 'DRIBBLE'
    | 'SAVE'
    | 'YELLOW_CARD'
    | 'RED_CARD'
    | 'SUBSTITUTION'
    | 'INJURY'
    | 'CORNER'
    | 'FREE_KICK'
    | 'THROW_IN'
    | 'GOAL_KICK';

/**
 * Visual event for canvas animation
 */
export interface VisualEvent {
    id: string;
    type: VisualEventType;
    minute: number;
    tick: number;
    
    // Spatial context
    position: SpatialPosition;
    
    // Involved entities
    playerId?: string;
    playerName?: string;
    teamId: string;
    targetPlayerId?: string;
    
    // Event-specific data
    metadata?: {
        // For passes/shots
        trajectory?: SpatialPosition[];
        success?: boolean;
        distance?: number;
        
        // For goals
        assistPlayerId?: string;
        goalType?: 'OPEN_PLAY' | 'PENALTY' | 'FREE_KICK' | 'CORNER' | 'OWN_GOAL';
        
        // For cards
        reason?: string;
        
        // For substitutions
        playerOutId?: string;
        playerOutName?: string;
        playerInId?: string;
        playerInName?: string;
        text?: string;
    };
}

// ============================================================
// BALL TRANSITIONS (Movement of the ball)
// ============================================================

/**
 * Ball transition - records the path and movement of the ball
 * Used for smooth animation of passes, shots, and goalkeeper saves
 */
export interface BallTransition {
    type: 'PASS' | 'SHOT' | 'GOAL' | 'SAVE' | 'CLEARANCE';
    fromPosition: SpatialPosition;
    toPosition: SpatialPosition;
    fromPlayerId: string;
    toPlayerId?: string;  // Receiving player or goalkeeper
    minute: number;
    tick: number;
    success: boolean;
    trajectory: SpatialPosition[];  // Intermediate waypoints for smooth animation
    duration: number;  // Frames to animate over
    ballHeight?: 'ground' | 'low' | 'high' | 'aerial';  // Ball height during transition
    description?: string;  // Goal, save, clearance details
}

// ============================================================
// MATCH STATE
// ============================================================

/**
 * Frame snapshot for a specific moment in the match
 */
export interface MatchFrame {
    minute: number;
    tick: number;
    
    // Ball state
    ball: V2BallState;
    
    // Player positions (22 players) - plain object for JSON serialization
    playerPositions: Record<string, SpatialPosition>;
    
    // Events in this frame
    events: VisualEvent[];
    
    // Ball transitions starting in this frame
    ballTransitions?: BallTransition[];

    // Phase 7: optional debug overlay payload per frame
    debug?: {
        intents: Array<{
            playerId: string;
            team: 'home' | 'away';
            from: SpatialPosition;
            to: SpatialPosition;
            job: RoleJob;
            priority: number;
            utilityScore: number;
            context: string;
        }>;
        defensive: {
            home: { presserId?: string; coverId?: string; lineX: number };
            away: { presserId?: string; coverId?: string; lineX: number };
        };
    };
}

export type TeamKey = 'home' | 'away';

export interface V2TelemetrySummary {
    frameCount: number;
    intentJobCounts: Record<string, number>;
    pressEvents: number;
    coverEvents: number;
    passSelection: {
        sampleCount: number;
        avgRisk: number;
        avgUtility: number;
        samples: Array<{
            minute: number;
            from: string;
            to: string;
            utility: number;
            risk: number;
            successProbability: number;
        }>;
    };
}

/**
 * V2 Match State - Extends base MatchState with spatial data
 */
export interface V2MatchState extends MatchState {
    // Spatial replay data
    frames: MatchFrame[];                          // All frames (config-driven; baseline 900 = 90 min × 10 ticks)
    
    // Optimized storage (key frames only)
    keyFrames?: MatchFrame[];                      // Goals, cards, set pieces only
    
    // Visual events
    visualEvents: VisualEvent[];                   // All canvas-renderable events
    
    // Ball movement transitions
    ballTransitions: BallTransition[];             // All ball movement paths
    
    // Formation metadata
    homeFormationCoordinates: Record<string, SpatialPosition>;
    awayFormationCoordinates: Record<string, SpatialPosition>;

    // Phase 7 aggregated telemetry
    telemetry?: V2TelemetrySummary;

    // Continuous movement/carry analytics (sampled every simulation tick)
    // Useful for future player heatmap and possession-space analysis.
    playerMovementAnalytics?: Record<string, {
        movementDistance: number;
        carryDistance: number;
        carrySeconds: number;
        zoneSeconds: {
            defensive: number;
            middle: number;
            attacking: number;
        };
        samples: number;
    }>;
}

// ============================================================
// MOVEMENT AI CONFIGURATION
// ============================================================

/**
 * Movement AI weights for player positioning
 */
export interface MovementWeights {
    ballAttraction: number;      // Pull toward ball (0-1)
    rolePosition: number;        // Stay near tactical position (0-1)
    spacing: number;             // Avoid crowding teammates (0-1)
    marking: number;             // Man-mark opponent (0-1)
}

/**
 * Player role-specific movement behavior
 */
export interface RoleMovementConfig {
    weights: MovementWeights;
    maxDistanceFromRole: number;     // Max yards from role position
    ballAttractionRadius: number;    // Only attracted if ball within X yards
}

// ============================================================
// SET PIECE POSITIONING
// ============================================================

/**
 * Set piece setup configuration
 */
export interface SetPieceSetup {
    type: 'CORNER' | 'FREE_KICK' | 'THROW_IN' | 'GOAL_KICK';
    ballPosition: SpatialPosition;
    
    // Player positioning
    attackingPositions: Map<string, SpatialPosition>;  // Player ID → target position
    defendingPositions: Map<string, SpatialPosition>;
    
    // Tactical instructions
    attackingStrategy?: 'NEAR_POST' | 'FAR_POST' | 'SHORT' | 'DIRECT';
    defendingStrategy?: 'ZONAL' | 'MAN_MARKING' | 'MIXED';
}

// ============================================================
// COLLISION DETECTION
// ============================================================

/**
 * Collision between two players
 */
export interface PlayerCollision {
    player1Id: string;
    player2Id: string;
    position: SpatialPosition;
    
    // Resolution
    separationVector: Velocity;  // Direction to push players apart
    tackleAttempted: boolean;    // Was this a tackle?
}

// ============================================================
// CANVAS RENDERING HINTS
// ============================================================

/**
 * Rendering hints for canvas optimization
 */
export interface RenderingHints {
    // Viewport culling
    viewportMin: SpatialPosition;
    viewportMax: SpatialPosition;
    
    // Detail level
    showPlayerNames: boolean;
    showJerseyNumbers: boolean;
    showMovementTrails: boolean;
    showTacticalOverlays: boolean;
    
    // Animation
    animationSpeed: number;  // 1x, 2x, 5x
    interpolateFrames: boolean;
}

// ============================================================
// EXPORTS
// ============================================================

export type {
    // Re-export base types for convenience
    PlayerState,
    TeamState,
    MatchState,
    MatchEventLog,
};
